repos:
  - repo: local
    hooks:
      - id: black-local
        name: black (local)
        entry: ./.venv/bin/black
        language: system
        types: [python]
      - id: isort-local
        name: isort (local)
        entry: ./.venv/bin/isort
        language: system
        types: [python]
      - id: ruff-local
        name: ruff (local)
        entry: ./.venv/bin/ruff
        language: system
        args: ["check", "--fix"]
        types: [python]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
