[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'

[tool.isort]
profile = 'black'
line_length = 88
known_first_party = ['df']

[tool.ruff]
line-length = 88
target-version = 'py310'
extend-ignore = ['E203']
select = ['E', 'F', 'W', 'C', 'B', 'C90', 'I']
