
# Define directories to add to PATH
directories=(
    "/usr/local/bin"
    "$HOME/.local/bin"
    "$HOME/.cargo/bin"
    "$HOME/.local/share/bob/nvim-bin" # Add nvim to path (with highest priority)
)

# Add directories to PATH if they exist
for dir in "${directories[@]}"; do
    [[ -d "$dir" ]] && path=("$dir" $path)
done

eval "$(starship init zsh)"

export PATH
export npm_config_prefix="$HOME/.local"
export NEOVIDE_MULTIGRID=1

# Source local zshrc if it exists
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local

# Aliases
alias de="distrobox-enter"
alias d="distrobox"
alias n="nvim"
alias nv="neovide"

# Zinit installation and setup
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load plugins with zinit
zinit light zsh-users/zsh-autosuggestions
zinit light marlonrichert/zsh-autocomplete

zinit ice wait lucid
zinit light zsh-users/zsh-syntax-highlighting
zinit ice wait lucid
zinit light zsh-users/zsh-completions
zinit ice wait lucid
zinit light agkozak/zsh-z

export ZSHZ_NO_RESOLVE_SYMLINKS=1
export ZSHZ_CASE=smart

