# ZSH Configuration

# Define directories to add to PATH
directories=(
    "/usr/local/bin"
    "$HOME/.local/bin"
    "$HOME/.cargo/bin"
    "$HOME/.local/share/bob/nvim-bin" # Add nvim to path (with highest priority)
)

# Add directories to PATH if they exist
for dir in "${directories[@]}"; do
    [[ -d "$dir" ]] && path=("$dir" $path)
done

# Initialize Starship, a cross-shell prompt
eval "$(starship init zsh)"

# Export environment variables
export PATH
export npm_config_prefix="$HOME/.local"
export NEOVIDE_MULTIGRID=1

# Source local zshrc if it exists
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local

# Define aliases for common commands
alias de="distrobox-enter"
alias d="distrobox"
alias n="nvim"
alias nv="neovide"
alias lg="lazygit"

# Install and setup Zinit, a flexible ZSH plugin manager
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi

# Source Zinit and load plugins
source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load plugins with zinit
zinit light-mode for \
    zsh-users/zsh-autosuggestions \
    marlonrichert/zsh-autocomplete \
    zsh-users/zsh-syntax-highlighting \
    zsh-users/zsh-completions \
    agkozak/zsh-z \
    zsh-users/zsh-history-substring-search

# Configure autocomplete and syntax highlighting
WORDCHARS='*?_-.[]~=&;!#$%^(){}<>' 
export ZSHZ_NO_RESOLVE_SYMLINKS=1
export ZSHZ_CASE=smart
zstyle ':autocomplete:*' delay 0
setopt autocd

# Configure history
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory

# Prefer case sensitive completion
bindkey '\t' menu-select
bindkey -M menuselect '^[[Z' reverse-menu-complete
zstyle ':completion:*' accept-exact '*(N)'
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}'
zstyle ':completion:*' case-sensitive true

# Hide duplicates in history
HISTORY_SUBSTRING_SEARCH_ENSURE_UNIQUE=1
setopt HIST_IGNORE_ALL_DUPS

# Configure key bindings
bindkey '^[[A' history-substring-search-up # or '\eOA'
bindkey '^[[B' history-substring-search-down # or '\eOB'
bindkey '^H' backward-kill-word
bindkey '^[[1;5C' forward-word
bindkey '^[[1;5D' backward-word
